// GENERATED by scripts/build-og.mjs from the same card table that renders public/og/*.png. Do not edit by hand.

/** An Open Graph card (1200x630 PNG in public/og/) and its alt text. `src` is a base-less site path. */
export interface OgCard {
  src: string;
  alt: string;
}

export const DEFAULT_OG: OgCard = { src: '/og/default.png', alt: 'CodersTrust: Learn. Earn. Prosper.' };

/** Path prefix -> section card, longest prefix first. */
const SECTION_CARDS: { prefix: string; card: OgCard }[] = [
  { prefix: '/nu-postgraduate-diploma/', card: { src: '/og/nu-postgraduate-diploma.png', alt: 'CodersTrust: NU Postgraduate Diploma. Build the digital skills employers are hiring for — alongside your degree.' } },
  { prefix: '/partner-with-us/', card: { src: '/og/partner-with-us.png', alt: 'CodersTrust: Partner with us. Co-design a youth-employment program with CodersTrust.' } },
  { prefix: '/investors/', card: { src: '/og/investors.png', alt: 'CodersTrust: Investors. Invest in the infrastructure of emerging-market work.' } },
  { prefix: '/our-model/', card: { src: '/og/our-model.png', alt: 'CodersTrust: Our model. How the CodersTrust model works.' } },
  { prefix: '/programs/', card: { src: '/og/programs.png', alt: 'CodersTrust: Programs. Choose the program that fits you.' } },
  { prefix: '/careers/', card: { src: '/og/careers.png', alt: 'CodersTrust: Careers. Help move educated, unemployed young people into paid digital work.' } },
  { prefix: '/contact/', card: { src: '/og/contact.png', alt: 'CodersTrust: Contact. Choose the route that fits you.' } },
  { prefix: '/impact/', card: { src: '/og/impact.png', alt: 'CodersTrust: Impact. What CodersTrust results show, what kind of evidence each one is, and what it does not show.' } },
  { prefix: '/about/', card: { src: '/og/about.png', alt: 'CodersTrust: About. CodersTrust turns educated, unemployed youth in emerging markets into job-ready digital professionals.' } },
  { prefix: '/news/', card: { src: '/og/news.png', alt: 'CodersTrust: News. Partnerships and MoUs, recognition, program events and leadership.' } },
];

/** The card for a base-less page path (for example "/impact/outcomes-2026/"); the default card when no section matches. */
export function ogCardFor(path: string): OgCard {
  for (const { prefix, card } of SECTION_CARDS) {
    if (path === prefix || path.startsWith(prefix)) return card;
  }
  return DEFAULT_OG;
}
